const COLORS={bg:'#111511',grid:'#273127',card:'#202720',card2:'#252d25',line:'#465446',text:'#f4f7ee',muted:'#a4b0a1',cue:'#bef264',warning:'#f7c948',danger:'#ff7f91'};
const ASSET_W=258,ASSET_H=198,NOTE_W=238,NOTE_H=124;

export class IntentCanvas {
  constructor(canvas,callbacks={}){
    this.canvas=canvas;this.ctx=canvas.getContext('2d');this.callbacks=callbacks;this.state={items:[],cues:[],motions:[]};this.camera={x:36,y:32,zoom:1};this.selectedId=null;this.mode=null;this.images=new Map();this.pointer=null;this.dpr=1;
    this.resizeObserver=new ResizeObserver(()=>this.resize());this.resizeObserver.observe(canvas.parentElement);this.bind();this.resize();
  }
  setState(state){this.state=state;this.preload();this.render()}
  setSelection(id){this.selectedId=id;this.render();this.callbacks.onSelection?.(this.getSelected(),this.selectionScreenRect())}
  getSelected(){return this.state.items.find(n=>n.id===this.selectedId)||null}
  setMode(mode){this.mode=mode;this.canvas.style.cursor=mode?.type==='cue'||mode?.type==='crop'||mode?.type==='motion'?'crosshair':'default';this.render()}
  clearMode(){this.setMode(null)}
  zoomBy(delta,anchor){const old=this.camera.zoom,next=Math.max(.35,Math.min(2.4,old+delta));const point=anchor||{x:this.cssWidth/2,y:this.cssHeight/2};const wx=(point.x-this.camera.x)/old,wy=(point.y-this.camera.y)/old;this.camera.zoom=next;this.camera.x=point.x-wx*next;this.camera.y=point.y-wy*next;this.render();this.callbacks.onViewChange?.(next)}
  fit(){if(!this.state.items.length){this.camera={x:36,y:32,zoom:1};this.render();return}const boxes=this.state.items.map(n=>this.bounds(n));const minX=Math.min(...boxes.map(b=>b.x)),minY=Math.min(...boxes.map(b=>b.y)),maxX=Math.max(...boxes.map(b=>b.x+b.w)),maxY=Math.max(...boxes.map(b=>b.y+b.h));const z=Math.max(.35,Math.min(1.25,Math.min((this.cssWidth-80)/(maxX-minX),(this.cssHeight-80)/(maxY-minY))));this.camera.zoom=z;this.camera.x=(this.cssWidth-(maxX-minX)*z)/2-minX*z;this.camera.y=(this.cssHeight-(maxY-minY)*z)/2-minY*z;this.render();this.callbacks.onViewChange?.(z)}
  centerForNewNode(){return this.toWorld({x:this.cssWidth*.5,y:this.cssHeight*.42})}
  selectionScreenRect(){const node=this.getSelected();if(!node)return null;const b=this.bounds(node),p=this.toScreen({x:b.x,y:b.y});return{x:p.x,y:p.y,w:b.w*this.camera.zoom,h:b.h*this.camera.zoom}}
  resize(){const r=this.canvas.parentElement.getBoundingClientRect();this.cssWidth=Math.max(1,r.width);this.cssHeight=Math.max(1,r.height);this.dpr=Math.min(window.devicePixelRatio||1,2);this.canvas.width=Math.round(this.cssWidth*this.dpr);this.canvas.height=Math.round(this.cssHeight*this.dpr);this.canvas.style.width=`${this.cssWidth}px`;this.canvas.style.height=`${this.cssHeight}px`;this.render()}
  bind(){this.canvas.addEventListener('pointerdown',e=>this.onDown(e));this.canvas.addEventListener('pointermove',e=>this.onMove(e));this.canvas.addEventListener('pointerup',e=>this.onUp(e));this.canvas.addEventListener('pointercancel',e=>this.onUp(e));this.canvas.addEventListener('wheel',e=>{e.preventDefault();this.zoomBy(e.deltaY<0?.08:-.08,this.eventPoint(e))},{passive:false});this.canvas.addEventListener('dblclick',e=>{const hit=this.hit(this.toWorld(this.eventPoint(e)));if(hit?.kind==='note')this.callbacks.onEditNote?.(hit)});this.canvas.addEventListener('keydown',e=>{if((e.key==='Delete'||e.key==='Backspace')&&this.selectedId){e.preventDefault();this.callbacks.onDelete?.(this.selectedId)}if(e.key==='Escape'){this.clearMode();this.callbacks.onModeCancel?.()}})}
  onDown(e){this.canvas.setPointerCapture?.(e.pointerId);const screen=this.eventPoint(e),world=this.toWorld(screen),hit=this.hit(world);this.pointer={id:e.pointerId,startScreen:screen,lastScreen:screen,startWorld:world,lastWorld:world,hitId:hit?.id,moved:false};
    if(this.mode?.type==='cue'){if(!this.mode.anchor){if(hit&&hit.kind!=='note'){const b=this.bounds(hit);this.mode.anchor={assetId:hit.id,x:clamp((world.x-b.x)/b.w),y:clamp((world.y-b.y)/(b.h-38))};this.setSelection(hit.id);if(this.mode.targetNoteId){this.callbacks.onCueComplete?.({...this.mode.anchor,noteId:this.mode.targetNoteId});this.clearMode()}else this.callbacks.onCueAnchor?.(hit)}else this.callbacks.onHint?.('Start the Cue on an asset or an exact visual region.')}else if(hit?.kind==='note'){this.callbacks.onCueComplete?.({...this.mode.anchor,noteId:hit.id});this.clearMode()}else this.callbacks.onHint?.('Finish the Cue on an instruction node.');return}
    if(this.mode?.type==='crop'){const node=this.state.items.find(n=>n.id===this.mode.nodeId);if(node&&hit?.id===node.id){const b=this.bounds(node),previewH=b.h-38;this.pointer.crop={nodeId:node.id,start:{x:clamp((world.x-b.x)/b.w),y:clamp((world.y-b.y)/previewH)},end:null};return}this.callbacks.onHint?.('Drag a crop rectangle inside the selected visual.');return}
    if(this.mode?.type==='motion'){const node=this.state.items.find(n=>n.id===this.mode.nodeId);if(node&&hit?.id===node.id){const b=this.bounds(node),previewH=b.h-38;this.pointer.motion={nodeId:node.id,started:performance.now(),samples:[{x:clamp((world.x-b.x)/b.w),y:clamp((world.y-b.y)/previewH),t:0}]};return}this.callbacks.onHint?.('Draw the movement directly over the selected visual.');return}
    if(hit){this.setSelection(hit.id);this.callbacks.onDragStart?.(hit);this.pointer.drag={node:hit,originX:hit.x,originY:hit.y}}else{this.setSelection(null);this.pointer.pan={originX:this.camera.x,originY:this.camera.y}}
  }
  onMove(e){if(!this.pointer||this.pointer.id!==e.pointerId)return;const s=this.eventPoint(e),w=this.toWorld(s);this.pointer.lastScreen=s;this.pointer.lastWorld=w;if(Math.hypot(s.x-this.pointer.startScreen.x,s.y-this.pointer.startScreen.y)>3)this.pointer.moved=true;
    if(this.pointer.drag){const dx=(s.x-this.pointer.startScreen.x)/this.camera.zoom,dy=(s.y-this.pointer.startScreen.y)/this.camera.zoom;this.pointer.drag.node.x=this.pointer.drag.originX+dx;this.pointer.drag.node.y=this.pointer.drag.originY+dy;this.render();this.callbacks.onSelection?.(this.getSelected(),this.selectionScreenRect());return}
    if(this.pointer.pan){this.camera.x=this.pointer.pan.originX+s.x-this.pointer.startScreen.x;this.camera.y=this.pointer.pan.originY+s.y-this.pointer.startScreen.y;this.render();return}
    if(this.pointer.crop){const n=this.state.items.find(x=>x.id===this.pointer.crop.nodeId),b=this.bounds(n),ph=b.h-38;this.pointer.crop.end={x:clamp((w.x-b.x)/b.w),y:clamp((w.y-b.y)/ph)};this.render();return}
    if(this.pointer.motion){const n=this.state.items.find(x=>x.id===this.pointer.motion.nodeId),b=this.bounds(n),ph=b.h-38,last=this.pointer.motion.samples.at(-1),next={x:clamp((w.x-b.x)/b.w),y:clamp((w.y-b.y)/ph),t:performance.now()-this.pointer.motion.started};if(!last||Math.hypot(next.x-last.x,next.y-last.y)>.008)this.pointer.motion.samples.push(next);this.render()}
  }
  onUp(e){if(!this.pointer||this.pointer.id!==e.pointerId)return;const p=this.pointer;this.pointer=null;
    if(p.drag&&p.moved)this.callbacks.onNodeMove?.(p.drag.node);
    if(p.crop?.end){const x=Math.min(p.crop.start.x,p.crop.end.x),y=Math.min(p.crop.start.y,p.crop.end.y),w=Math.abs(p.crop.end.x-p.crop.start.x),h=Math.abs(p.crop.end.y-p.crop.start.y);if(w>.04&&h>.04)this.callbacks.onCrop?.(p.crop.nodeId,{x,y,w,h});else this.callbacks.onHint?.('Draw a larger crop region.');this.clearMode()}
    if(p.motion){if(p.motion.samples.length>=3)this.callbacks.onMotion?.(p.motion.nodeId,p.motion.samples);else this.callbacks.onHint?.('The motion take was too short. Draw a longer path.');this.clearMode()}
    this.render()
  }
  eventPoint(e){const r=this.canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}
  toWorld(p){return{x:(p.x-this.camera.x)/this.camera.zoom,y:(p.y-this.camera.y)/this.camera.zoom}}
  toScreen(p){return{x:p.x*this.camera.zoom+this.camera.x,y:p.y*this.camera.zoom+this.camera.y}}
  bounds(n){return{x:n.x,y:n.y,w:n.w|| (n.kind==='note'?NOTE_W:ASSET_W),h:n.h||(n.kind==='note'?NOTE_H:ASSET_H)}}
  hit(world){for(let i=this.state.items.length-1;i>=0;i--){const n=this.state.items[i],b=this.bounds(n);if(world.x>=b.x&&world.x<=b.x+b.w&&world.y>=b.y&&world.y<=b.y+b.h)return n}return null}
  preload(){for(const n of this.state.items){if(!['image','webpage'].includes(n.kind)||!n.dataUrl||this.images.has(n.id))continue;const img=new Image();img.onload=()=>this.render();img.src=n.dataUrl;this.images.set(n.id,img)}}
  render(){if(!this.ctx||!this.cssWidth)return;const c=this.ctx;c.setTransform(this.dpr,0,0,this.dpr,0,0);c.clearRect(0,0,this.cssWidth,this.cssHeight);c.fillStyle=COLORS.bg;c.fillRect(0,0,this.cssWidth,this.cssHeight);this.drawGrid(c);c.save();c.translate(this.camera.x,this.camera.y);c.scale(this.camera.zoom,this.camera.zoom);this.drawCues(c);for(const n of this.state.items)this.drawNode(c,n);this.drawMotions(c);this.drawActiveGesture(c);c.restore();this.callbacks.onSelection?.(this.getSelected(),this.selectionScreenRect())}
  drawGrid(c){const size=24*this.camera.zoom,ox=((this.camera.x%size)+size)%size,oy=((this.camera.y%size)+size)%size;c.fillStyle=COLORS.grid;for(let x=ox;x<this.cssWidth;x+=size)for(let y=oy;y<this.cssHeight;y+=size){c.beginPath();c.arc(x,y,Math.max(.55,this.camera.zoom*.7),0,Math.PI*2);c.fill()}}
  drawCues(c){for(const cue of this.state.cues){const a=this.state.items.find(n=>n.id===cue.assetId),note=this.state.items.find(n=>n.id===cue.noteId);if(!a)continue;const ab=this.bounds(a),nb=note?this.bounds(note):null,x1=ab.x+ab.w*cue.x,y1=ab.y+(ab.h-38)*cue.y,x2=nb?nb.x:ab.x+ab.w+100,y2=nb?nb.y+nb.h*.5:y1+45;c.strokeStyle=note?COLORS.muted:COLORS.warning;c.lineWidth=2/this.camera.zoom;c.setLineDash(note?[]:[7/this.camera.zoom,5/this.camera.zoom]);c.beginPath();c.moveTo(x1,y1);c.bezierCurveTo(x1+70,y1,x2-70,y2,x2,y2);c.stroke();c.setLineDash([]);c.fillStyle=COLORS.cue;c.beginPath();c.arc(x1,y1,4/this.camera.zoom,0,Math.PI*2);c.fill()}}
  drawNode(c,n){const b=this.bounds(n),selected=n.id===this.selectedId,intentional=this.isIntentional(n);c.save();c.shadowColor='rgba(0,0,0,.24)';c.shadowBlur=14;c.shadowOffsetY=7;roundRect(c,b.x,b.y,b.w,b.h,12);c.fillStyle=n.kind==='note'?'#252d25':COLORS.card;c.fill();c.shadowColor='transparent';c.lineWidth=(selected?2:1)/this.camera.zoom;c.strokeStyle=selected?COLORS.cue:(intentional?'#6f873f':COLORS.line);c.stroke();c.beginPath();roundRect(c,b.x,b.y,b.w,b.h,12);c.clip();if(n.kind==='note')this.drawNote(c,n,b);else this.drawAsset(c,n,b);c.restore()}
  drawAsset(c,n,b){const previewH=b.h-38,img=this.images.get(n.id);c.fillStyle='#0d110d';c.fillRect(b.x,b.y,b.w,previewH);if(img?.complete&&img.naturalWidth){coverImage(c,img,b.x,b.y,b.w,previewH)}else{c.fillStyle='#303a30';c.font='700 12px Inter,system-ui';c.textAlign='center';c.textBaseline='middle';c.fillText(n.kind==='video'?'VIDEO':n.kind==='document'?'DOCUMENT':'VISUAL',b.x+b.w/2,b.y+previewH/2)}c.fillStyle=COLORS.card2;c.fillRect(b.x,b.y+previewH,b.w,38);c.textAlign='left';c.textBaseline='alphabetic';c.fillStyle=COLORS.text;c.font='650 11px Inter,system-ui';c.fillText(ellipsis(c,n.name||'Untitled asset',b.w-94),b.x+10,b.y+previewH+16);c.fillStyle=COLORS.muted;c.font='500 9px Inter,system-ui';c.fillText((n.role||n.provenance||n.kind).toUpperCase(),b.x+10,b.y+previewH+29);const status=this.isIntentional(n)?'INTENTIONAL':'IDLE';c.fillStyle=this.isIntentional(n)?'#35481e':'#303a30';roundRect(c,b.x+b.w-74,b.y+previewH+10,64,17,9);c.fill();c.fillStyle=this.isIntentional(n)?'#e9ffc0':'#b6c0b3';c.font='700 7px Inter,system-ui';c.textAlign='center';c.fillText(status,b.x+b.w-42,b.y+previewH+22)}
  drawNote(c,n,b){c.fillStyle=COLORS.cue;c.font='750 8px Inter,system-ui';c.textAlign='left';c.fillText('INSTRUCTION',b.x+13,b.y+19);c.fillStyle=COLORS.text;c.font='560 12px Inter,system-ui';wrapText(c,n.text||'Empty instruction',b.x+13,b.y+42,b.w-26,18,4);if(n.changed){c.fillStyle=COLORS.cue;c.fillRect(b.x,b.y,3,b.h)}}
  drawMotions(c){for(const m of this.state.motions){const n=this.state.items.find(x=>x.id===m.assetId);if(!n||!m.samples?.length)continue;const b=this.bounds(n),ph=b.h-38;c.strokeStyle=COLORS.cue;c.lineWidth=3/this.camera.zoom;c.setLineDash([5/this.camera.zoom,5/this.camera.zoom]);c.beginPath();m.samples.forEach((s,i)=>{const x=b.x+b.w*s.x,y=b.y+ph*s.y;i?c.lineTo(x,y):c.moveTo(x,y)});c.stroke();c.setLineDash([])}}
  drawActiveGesture(c){const crop=this.pointer?.crop;if(crop?.end){const n=this.state.items.find(x=>x.id===crop.nodeId),b=this.bounds(n),ph=b.h-38,x=b.x+b.w*Math.min(crop.start.x,crop.end.x),y=b.y+ph*Math.min(crop.start.y,crop.end.y),w=b.w*Math.abs(crop.end.x-crop.start.x),h=ph*Math.abs(crop.end.y-crop.start.y);c.fillStyle='rgba(190,242,100,.12)';c.fillRect(x,y,w,h);c.strokeStyle=COLORS.cue;c.lineWidth=2/this.camera.zoom;c.strokeRect(x,y,w,h)}const motion=this.pointer?.motion;if(motion?.samples?.length){const n=this.state.items.find(x=>x.id===motion.nodeId),b=this.bounds(n),ph=b.h-38;c.strokeStyle=COLORS.cue;c.lineWidth=3/this.camera.zoom;c.beginPath();motion.samples.forEach((s,i)=>{const x=b.x+b.w*s.x,y=b.y+ph*s.y;i?c.lineTo(x,y):c.moveTo(x,y)});c.stroke()}}
  isIntentional(n){return Boolean(n.intentional||n.role||this.state.cues.some(c=>c.assetId===n.id||c.noteId===n.id)||this.state.motions.some(m=>m.assetId===n.id))}
}

function clamp(n){return Math.max(0,Math.min(1,n))}function roundRect(c,x,y,w,h,r){const rr=Math.min(r,w/2,h/2);c.beginPath();c.moveTo(x+rr,y);c.arcTo(x+w,y,x+w,y+h,rr);c.arcTo(x+w,y+h,x,y+h,rr);c.arcTo(x,y+h,x,y,rr);c.arcTo(x,y,x+w,y,rr);c.closePath()}function coverImage(c,img,x,y,w,h){const s=Math.max(w/img.naturalWidth,h/img.naturalHeight),sw=w/s,sh=h/s,sx=(img.naturalWidth-sw)/2,sy=(img.naturalHeight-sh)/2;c.drawImage(img,sx,sy,sw,sh,x,y,w,h)}function ellipsis(c,text,max){if(c.measureText(text).width<=max)return text;let out=text;while(out.length>2&&c.measureText(`${out}…`).width>max)out=out.slice(0,-1);return `${out}…`}function wrapText(c,text,x,y,maxWidth,lineHeight,maxLines){const words=String(text).split(/\s+/);let line='',lines=[];for(const word of words){const test=line?`${line} ${word}`:word;if(c.measureText(test).width>maxWidth&&line){lines.push(line);line=word}else line=test}if(line)lines.push(line);lines.slice(0,maxLines).forEach((value,i)=>c.fillText(i===maxLines-1&&lines.length>maxLines?`${ellipsis(c,value,maxWidth-5)}…`:value,x,y+i*lineHeight))}
