import {IntentCanvas} from './canvas-engine.js';
const $=selector=>document.querySelector(selector),runtimeReady=Boolean(globalThis.chrome?.runtime?.sendMessage);
const roles=[['Target','The visual or region that should change.'],['Reference','Required visual evidence for this send.'],['Preserve','Keep identity, content, or appearance unchanged.'],['Style','Contribute visual language or treatment.'],['Structure','Contribute layout, hierarchy, or composition.'],['Context','Inform the answer without forcing attachment.']];
let context,state,selectedId=null,editingNoteId=null,videoNodeId=null,history=[],future=[];
const defaultState=()=>({version:2,items:[],cues:[],motions:[],submissions:[],uploaded:{},updatedAt:Date.now()});
const id=prefix=>`${prefix}_${crypto.randomUUID().slice(0,10)}`;
const engine=new IntentCanvas($('#intent-canvas'),{
  onSelection:(node,rect)=>selectionChanged(node,rect),onNodeMove:()=>save(),onEditNote:node=>openNote(node),onDelete:nodeId=>deleteNode(nodeId),onHint:announce,
  onDragStart:()=>checkpoint(),
  onCueAnchor:()=>setModeBanner('Target locked. Select the instruction node this Cue should control.'),onCueComplete:cue=>{checkpoint();state.cues.push({id:id('cue'),...cue,createdAt:Date.now()});saveRender();announce('Cue resolved.')},
  onCrop:(nodeId,bounds)=>createCrop(nodeId,bounds),onMotion:(nodeId,samples)=>addMotion(nodeId,samples),onModeCancel:clearModeUI,onViewChange:z=>$('#zoom-label').textContent=`${Math.round(z*100)}%`
});

async function init(){
  if(runtimeReady){const response=await chrome.runtime.sendMessage({type:'active-context'});context=response.context;const key=sessionKey();const stored=await chrome.storage.local.get(key);state=migrateState(stored[key]||defaultState());const health=await chrome.runtime.sendMessage({type:'health'});$('#service-state').textContent=health.ok?`Local intelligence · ${health.mode||'ready'}`:'Local intelligence unavailable'}
  else{context={platform:'Preview',title:'Canvas review',url:location.href,fingerprint:'preview'};state=previewState();$('#service-state').textContent='Design preview'}
  $('#destination-label').textContent=context.platform;engine.setState(state);updateUI();
}
function sessionKey(){return`viscue:session:${context.fingerprint}`}
function migrateState(input){return{...defaultState(),...input,items:(input.items||[]).map((n,index)=>({...n,x:Number.isFinite(n.x)?n.x:70+(index%3)*290,y:Number.isFinite(n.y)?n.y:60+Math.floor(index/3)*235,w:n.w||undefined,h:n.h||undefined})),cues:input.cues||[],motions:input.motions||[]}}
async function save(){state.updatedAt=Date.now();$('#save-state').textContent='Saving canvas…';if(runtimeReady)await chrome.storage.local.set({[sessionKey()]:state});$('#save-state').textContent='Canvas saved locally';updateUI()}
function saveRender(){engine.setState(state);save()}
function checkpoint(){history.push(structuredClone(state));if(history.length>50)history.shift();future=[]}
function undo(){if(!history.length)return;future.push(structuredClone(state));state=history.pop();selectedId=null;engine.setSelection(null);saveRender()}
function redo(){if(!future.length)return;history.push(structuredClone(state));state=future.pop();selectedId=null;engine.setSelection(null);saveRender()}
function selected(){return state.items.find(n=>n.id===selectedId)||null}
function intentional(n){return Boolean(n.intentional||n.role||state.cues.some(c=>c.assetId===n.id||c.noteId===n.id)||state.motions.some(m=>m.assetId===n.id))}

function selectionChanged(node,rect){selectedId=node?.id||null;renderContextToolbar(node,rect);renderInspector(node)}
function renderContextToolbar(node,rect){const toolbar=$('#context-toolbar');if(!node||!rect){toolbar.classList.add('hidden');return}const actions=node.kind==='note'?[['edit','Edit'],['cue','Connect'],['duplicate','Duplicate'],['delete','Delete']]:[['role','Role'],[node.kind==='video'?'frame':'crop',node.kind==='video'?'Frame':node.kind==='document'?'Scope':'Crop'],...(['image','webpage'].includes(node.kind)?[['motion','Motion']]:[]),['duplicate','Duplicate'],['delete','Delete']];toolbar.innerHTML=actions.map(([action,label])=>`<button type="button" data-action="${action}" class="${action==='delete'?'danger':''}">${label}</button>`).join('');toolbar.style.left=`${Math.max(72,Math.min($('.stage').clientWidth-72,rect.x+rect.w/2))}px`;toolbar.style.top=`${Math.max(46,rect.y-8)}px`;toolbar.classList.remove('hidden');toolbar.querySelectorAll('button').forEach(button=>button.onclick=()=>performAction(button.dataset.action,node))}
function renderInspector(node){const empty=$('#inspector-empty'),content=$('#inspector-content');if(!node){empty.classList.remove('hidden');content.classList.add('hidden');return}empty.classList.add('hidden');content.classList.remove('hidden');const cueCount=state.cues.filter(c=>c.assetId===node.id||c.noteId===node.id).length,motionCount=state.motions.filter(m=>m.assetId===node.id).length,status=intentional(node)?'Intentional':'Idle';content.innerHTML=`<p class="section-label">${node.kind==='note'?'INSTRUCTION NODE':'SOURCE NODE'}</p><h2>${escapeHtml(node.kind==='note'?node.text:node.name)}</h2><span class="status-chip ${intentional(node)?'intentional':''}">${status}</span><div class="inspector-section"><div class="inspector-row"><span>Type</span><strong>${escapeHtml(node.kind)}</strong></div><div class="inspector-row"><span>Role</span><strong>${escapeHtml(node.role||'Not assigned')}</strong></div><div class="inspector-row"><span>Cues</span><strong>${cueCount}</strong></div><div class="inspector-row"><span>Motion takes</span><strong>${motionCount}</strong></div>${node.provenance?`<div class="inspector-row"><span>Provenance</span><strong>${escapeHtml(node.provenance)}</strong></div>`:''}${node.detached?'<p>Original source is missing. This intentional child will be sent as a standalone visual.</p>':''}</div><div class="inspector-actions" id="inspector-actions"></div>`;const actions=node.kind==='note'?[['edit','Edit note'],['cue','Create Cue'],['duplicate','Duplicate'],['delete','Delete']]:[['role','Set role'],[node.kind==='video'?'frame':'crop',node.kind==='video'?'Extract frame':node.kind==='document'?'Set scope':'Crop region'],...(['image','webpage'].includes(node.kind)?[['motion','Record motion']]:[]),['duplicate','Duplicate'],['delete','Delete']];$('#inspector-actions').innerHTML=actions.map(([a,l])=>`<button type="button" data-action="${a}">${l}</button>`).join('');$('#inspector-actions').querySelectorAll('button').forEach(b=>b.onclick=()=>performAction(b.dataset.action,node))}
function performAction(action,node){if(action==='edit')openNote(node);if(action==='cue')startCue(node.kind==='note'?node:null);if(action==='role')openRole(node);if(action==='crop')startCrop(node);if(action==='frame')openFrame(node);if(action==='motion')startMotion(node);if(action==='duplicate')duplicateNode(node);if(action==='delete')deleteNode(node.id)}

async function addFiles(files){for(const file of files){checkpoint();const kind=file.type.startsWith('image/')?'image':file.type.startsWith('video/')?'video':'document',dataUrl=await readFile(file),pos=engine.centerForNewNode();const node={id:id('asset'),kind,name:file.name,dataUrl,mime:file.type||mimeFromName(file.name),x:pos.x+(state.items.length%4)*24,y:pos.y+(state.items.length%4)*24,hash:await digest(dataUrl)};state.items.push(node);selectedId=node.id}saveRender();engine.setSelection(selectedId);announce(`${files.length} asset${files.length===1?'':'s'} added.`)}
async function captureView(){try{const response=runtimeReady?await chrome.runtime.sendMessage({type:'capture-page',tabId:context.tabId}):null;if(!response?.ok)throw new Error(response?.error||'Capture is only available in the installed extension.');checkpoint();const pos=engine.centerForNewNode(),node={id:id('view'),kind:'webpage',name:response.title||'Captured view',dataUrl:response.dataUrl,mime:'image/png',sourceUrl:response.url,provenance:`${new URL(response.url).hostname} · captured ${new Date().toLocaleTimeString()}`,x:pos.x,y:pos.y,hash:await digest(response.dataUrl),intentional:true};state.items.push(node);saveRender();engine.setSelection(node.id);announce('Current webpage view added with URL and capture-time provenance.')}catch(error){announce(error.message,true)}}
function openNote(node=null){editingNoteId=node?.id||null;$('#note-dialog-title').textContent=node?'Edit note':'Add note';$('#note-text').value=node?.text||'';$('#note-dialog').showModal();setTimeout(()=>$('#note-text').focus(),50)}
function saveNote(){const text=$('#note-text').value.trim();if(!text)return false;checkpoint();if(editingNoteId){const note=state.items.find(n=>n.id===editingNoteId);note.text=text;note.changed=true;selectedId=note.id}else{const pos=engine.centerForNewNode(),note={id:id('note'),kind:'note',name:'Instruction',text,x:pos.x,y:pos.y};state.items.push(note);selectedId=note.id}saveRender();engine.setSelection(selectedId);return true}
function openRole(node){selectedId=node.id;$('#role-options').innerHTML=roles.map(([name,description])=>`<button class="role-option" type="button" data-role="${name}"><strong>${name}</strong><small>${description}</small></button>`).join('');$('#role-options').querySelectorAll('button').forEach(button=>button.onclick=()=>{checkpoint();node.role=button.dataset.role;node.intentional=true;$('#role-dialog').close();saveRender();engine.setSelection(node.id);announce(`${button.dataset.role} role assigned.`)});$('#role-dialog').showModal()}
function startCue(targetNote=null){engine.setMode({type:'cue',anchor:null,targetNoteId:targetNote?.id});setModeBanner(targetNote?'Select the exact source region this instruction controls.':'Select an exact region, then select its instruction node.');$('#start-cue').classList.add('active')}
function startCrop(node){if(!['image','webpage'].includes(node.kind)){if(node.kind==='document')return openRole(node);return announce('Crop is available for still visuals and captured views.')}engine.setSelection(node.id);engine.setMode({type:'crop',nodeId:node.id});setModeBanner('Drag a precise rectangle over the visual. The original stays clean.');announce('Crop mode started.')}
function startMotion(node){engine.setSelection(node.id);engine.setMode({type:'motion',nodeId:node.id});setModeBanner('Draw the movement directly over the target. Release to save the motion take.');announce('Record Motion started.')}
function clearModeUI(){$('#mode-banner').classList.add('hidden');$('#start-cue').classList.remove('active')}
function setModeBanner(text){const banner=$('#mode-banner');banner.textContent=text;banner.classList.remove('hidden')}
async function createCrop(nodeId,bounds){const source=state.items.find(n=>n.id===nodeId);try{checkpoint();const image=await loadImage(source.dataUrl),out=document.createElement('canvas');out.width=Math.max(1,Math.min(1800,Math.round(image.naturalWidth*bounds.w)));out.height=Math.max(1,Math.min(1800,Math.round(image.naturalHeight*bounds.h)));out.getContext('2d').drawImage(image,image.naturalWidth*bounds.x,image.naturalHeight*bounds.y,image.naturalWidth*bounds.w,image.naturalHeight*bounds.h,0,0,out.width,out.height);const dataUrl=out.toDataURL('image/png'),child={id:id('crop'),kind:'image',name:`${source.name} · crop`,dataUrl,mime:'image/png',parentId:source.id,provenance:`Crop · ${Math.round(bounds.x*100)}–${Math.round((bounds.x+bounds.w)*100)}% x · ${Math.round(bounds.y*100)}–${Math.round((bounds.y+bounds.h)*100)}% y`,transform:bounds,x:source.x+(source.w||258)+40,y:source.y,hash:await digest(dataUrl),intentional:true};state.items.push(child);saveRender();engine.setSelection(child.id);clearModeUI();announce('Clean derived crop added with source provenance.')}catch{announce('This source could not be cropped.',true)}}
function addMotion(nodeId,samples){checkpoint();const first=samples[0],last=samples.at(-1),duration=Math.max(120,Math.round(last.t||0)),motion={id:id('motion'),assetId:nodeId,samples:simplify(samples),duration,description:motionPhrase(samples,duration),createdAt:Date.now()};state.motions.push(motion);const node=state.items.find(n=>n.id===nodeId);node.intentional=true;saveRender();engine.setSelection(nodeId);clearModeUI();announce('Motion take recorded and bound to this exact target.')}
function openFrame(node){videoNodeId=node.id;const video=$('#frame-video');video.src=node.dataUrl;$('#frame-time').value=500;video.onloadedmetadata=()=>{video.currentTime=(video.duration||0)*.5;updateFrameLabel(video.currentTime)};$('#video-dialog').showModal()}
async function extractFrame(){const source=state.items.find(n=>n.id===videoNodeId),video=$('#frame-video');if(!source||!video.videoWidth)return false;checkpoint();const out=document.createElement('canvas');out.width=video.videoWidth;out.height=video.videoHeight;out.getContext('2d').drawImage(video,0,0);const dataUrl=out.toDataURL('image/png'),time=video.currentTime,child={id:id('frame'),kind:'image',name:`${source.name} · ${formatTime(time)}`,dataUrl,mime:'image/png',parentId:source.id,provenance:`Frame · ${formatTime(time)}`,timeMs:Math.round(time*1000),x:source.x+(source.w||258)+40,y:source.y,hash:await digest(dataUrl),intentional:true};state.items.push(child);saveRender();engine.setSelection(child.id);announce('Video frame extracted with precise timestamp provenance.');return true}
function duplicateNode(node){checkpoint();const copy=structuredClone(node);copy.id=id(node.kind==='note'?'note':'asset');copy.x+=34;copy.y+=34;copy.name=node.kind==='note'?node.name:`${node.name} · copy`;copy.changed=true;state.items.push(copy);saveRender();engine.setSelection(copy.id)}
function deleteNode(nodeId){const node=state.items.find(n=>n.id===nodeId);if(!node)return;checkpoint();for(const child of state.items.filter(n=>n.parentId===nodeId)){if(intentional(child))child.detached=true;else state.items=state.items.filter(n=>n.id!==child.id)}state.items=state.items.filter(n=>n.id!==nodeId);state.cues=state.cues.filter(c=>c.assetId!==nodeId&&c.noteId!==nodeId);state.motions=state.motions.filter(m=>m.assetId!==nodeId);selectedId=null;engine.setSelection(null);saveRender();announce(`${node.kind==='note'?'Instruction':'Asset'} deleted.`)}

function openPreflight(){const unresolved=state.cues.filter(c=>!state.items.some(n=>n.id===c.noteId)),assets=state.items.filter(n=>n.kind!=='note'&&intentional(n)),unused=state.items.filter(n=>n.kind!=='note'&&!intentional(n)),detached=assets.filter(n=>n.detached);const rows=[];if(!assets.length)rows.push(['warning','Nothing is intentional','Assign a role, create a Cue, or record motion before sending.']);if(unresolved.length)rows.push(['warning',`${unresolved.length} unresolved Cue${unresolved.length===1?'':'s'}`,'Every target must resolve to an instruction.']);if(detached.length)rows.push(['warning',`${detached.length} detached derived asset${detached.length===1?'':'s'}`,'They will be sent as standalone visuals without claiming live parent context.']);if(assets.length)rows.push(['ready',`${assets.length} clean reference${assets.length===1?'':'s'} selected`,'Viscue will attach these automatically; Cue lines and motion trails remain internal.']);if(unused.length)rows.push(['ready',`${unused.length} idle reference${unused.length===1?'':'s'} excluded`,'Presence is not intent, so unused assets stay out of the handoff.']);$('#preflight-list').innerHTML=rows.map(([type,title,copy])=>`<div class="preflight-item ${type}"><strong>${title}</strong><span>${copy}</span></div>`).join('');$('#confirm-handoff').disabled=!assets.length||Boolean(unresolved.length);$('#handoff-progress').className='handoff-progress hidden';$('#handoff-progress').textContent='';$('#preflight-dialog').showModal()}
async function compileAndSend(){const button=$('#confirm-handoff'),progress=$('#handoff-progress');button.disabled=true;button.textContent='Compiling intent';progress.className='handoff-progress';progress.textContent='Resolving relationships and selecting the minimum clean reference set…';try{if(!runtimeReady)throw new Error('Install the extension in Chrome to test the automatic destination handoff.');const response=await chrome.runtime.sendMessage({type:'compile',payload:{context,session:state,graph:buildGraph()}});if(!response.ok)throw new Error(response.error||'Intent compilation failed.');const attachments=(response.attachments||[]).map(manifest=>{const node=state.items.find(n=>n.id===manifest.id);return node?{id:node.id,name:node.name,mime:node.mime||mimeFromName(node.name),dataUrl:node.dataUrl,kind:node.kind,hash:node.hash}:null}).filter(Boolean);progress.textContent=`Compiled. Attaching ${attachments.length} clean reference${attachments.length===1?'':'s'} to ${context.platform}…`;const handoff=await chrome.runtime.sendMessage({type:'handoff',tabId:context.tabId,prompt:response.final_prompt,attachments,submit:$('#auto-submit').checked});if(!handoff.ok)throw new Error(handoff.error||'Destination handoff failed.');checkpoint();state.submissions.push({id:id('submission'),at:Date.now(),destination:context.platform,prompt:response.final_prompt,attachments:attachments.map(a=>({id:a.id,hash:a.hash,name:a.name})),provider:response.provider});attachments.forEach(a=>state.uploaded[a.hash]={platform:context.platform,at:Date.now()});await save();progress.className='handoff-progress success';progress.textContent=handoff.submitted?`Sent automatically to ${context.platform}: prompt inserted and ${handoff.attached} reference${handoff.attached===1?'':'s'} attached.`:`Handoff is ready in ${context.platform}: prompt inserted and ${handoff.attached} reference${handoff.attached===1?'':'s'} attached.`;button.textContent='Sent';announce(progress.textContent)}catch(error){progress.className='handoff-progress error';progress.textContent=error.message;button.disabled=false;button.textContent='Try again';announce(error.message,true)}}
function buildGraph(){return{destination:context.platform,items:state.items.map(n=>({id:n.id,kind:n.kind,name:n.name,text:n.text,role:n.role,intentional:intentional(n),parentId:n.parentId,detached:n.detached,provenance:n.provenance,hash:n.hash,mime:n.mime})),cues:state.cues.map(c=>({...c,instruction:state.items.find(n=>n.id===c.noteId)?.text})),motions:state.motions.map(m=>({...m,description:m.description}))}}

function updateUI(){$('#empty-state').classList.toggle('hidden',state.items.length>0);$('#undo').disabled=!history.length;$('#redo').disabled=!future.length;const assets=state.items.filter(n=>n.kind!=='note'&&intentional(n)),unresolved=state.cues.filter(c=>!state.items.some(n=>n.id===c.noteId));$('#intent-summary').textContent=unresolved.length?`${unresolved.length} unresolved Cue${unresolved.length===1?'':'s'}`:assets.length?`${assets.length} intentional reference${assets.length===1?'':'s'} ready`:'No intentional references yet';$('#canvas-node-list').innerHTML=state.items.map(n=>`<button type="button" data-node-id="${n.id}">${escapeHtml(n.kind==='note'?`Instruction: ${n.text}`:`${n.kind}: ${n.name}`)}</button>`).join('');$('#canvas-node-list').querySelectorAll('button').forEach(button=>{const selectNode=()=>engine.setSelection(button.dataset.nodeId);button.onclick=selectNode;button.onfocus=selectNode})}
function announce(message,error=false){$('#live-region').textContent=message;$('#service-state').textContent=message;$('#service-state').style.color=error?'var(--danger)':'';clearTimeout(announce.timer);announce.timer=setTimeout(()=>{$('#service-state').style.color='';$('#service-state').textContent=runtimeReady?'Local intelligence ready':'Design preview'},4500)}
function previewState(){return{...defaultState(),items:[{id:'preview_base',kind:'image',name:'Product reference.png',x:80,y:90,role:'Target',intentional:true},{id:'preview_style',kind:'document',name:'Brand system.pdf',x:420,y:250,role:'Style',intentional:true},{id:'preview_note',kind:'note',name:'Instruction',text:'Use the material treatment from the brand reference. Preserve the logo exactly.',x:435,y:70}],cues:[{id:'preview_cue',assetId:'preview_base',noteId:'preview_note',x:.62,y:.44}],motions:[],submissions:[],uploaded:{}}}

$('#file-input').addEventListener('change',event=>{addFiles([...event.target.files]);event.target.value=''});$('#empty-add-asset').onclick=()=>$('#file-input').click();$('#add-note').onclick=()=>openNote();$('#empty-add-note').onclick=()=>openNote();$('#start-cue').onclick=()=>startCue();$('#capture-view').onclick=captureView;$('#undo').onclick=undo;$('#redo').onclick=redo;$('#send-intent').onclick=openPreflight;$('#expand-workspace').onclick=()=>runtimeReady&&chrome.runtime.sendMessage({type:'expand-workspace'});$('#zoom-in').onclick=()=>engine.zoomBy(.12);$('#zoom-out').onclick=()=>engine.zoomBy(-.12);$('#fit-canvas').onclick=()=>engine.fit();$('#save-note').onclick=event=>{if(!saveNote())event.preventDefault()};$('#extract-frame').onclick=event=>{event.preventDefault();extractFrame().then(ok=>ok&&$('#video-dialog').close())};$('#frame-time').oninput=event=>{const video=$('#frame-video'),time=(video.duration||0)*(Number(event.target.value)/1000);video.currentTime=time;updateFrameLabel(time)};$('#confirm-handoff').onclick=event=>{event.preventDefault();compileAndSend()};

function updateFrameLabel(time){$('#frame-time-label').textContent=formatTime(time)}function formatTime(seconds){const min=Math.floor(seconds/60),sec=Math.floor(seconds%60),ms=Math.floor((seconds%1)*1000);return`${String(min).padStart(2,'0')}:${String(sec).padStart(2,'0')}.${String(ms).padStart(3,'0')}`}function readFile(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file)})}function loadImage(src){return new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=reject;image.src=src})}async function digest(value){const hash=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value));return`sha256:${[...new Uint8Array(hash)].map(v=>v.toString(16).padStart(2,'0')).join('')}`}function simplify(samples){return samples.filter((sample,index)=>index===0||index===samples.length-1||Math.hypot(sample.x-samples[index-1].x,sample.y-samples[index-1].y)>.018)}function motionPhrase(samples,duration){const a=samples[0],b=samples.at(-1),dx=b.x-a.x,dy=b.y-a.y,h=Math.abs(dx)>.08?(dx>0?'right':'left'):'',v=Math.abs(dy)>.08?(dy>0?'down':'up'):'',direction=[v,h].filter(Boolean).join('-')||'in place',distance=Math.hypot(dx,dy);return`Move the selected target ${direction} ${distance>.55?'a long distance':distance>.22?'a moderate distance':'slightly'} over ${(duration/1000).toFixed(1)} seconds.`}function mimeFromName(name=''){const ext=name.split('.').pop().toLowerCase();return({png:'image/png',jpg:'image/jpeg',jpeg:'image/jpeg',webp:'image/webp',gif:'image/gif',mp4:'video/mp4',webm:'video/webm',pdf:'application/pdf',txt:'text/plain',doc:'application/msword',docx:'application/vnd.openxmlformats-officedocument.wordprocessingml.document'})[ext]||'application/octet-stream'}function escapeHtml(value=''){return String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]))}
init().catch(error=>announce(error.message,true));
